enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MatadorProBr/revanced-extended-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
included-patches = "'Add splash animation' 'MaterialYou'"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm-v7a"
patches-version = "v2.224.0-dev.5"
integrations-version = "v0.151.0-dev.5"

[Music]
build-mode = "module"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm-v7a"
patches-version = "v2.224.0-dev.5"
integrations-version = "v0.151.0-dev.5"

[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
